name: Deploy

on:
  push:
    branches:
      - main

jobs:
  tf_fmt:
    name: Build Infra
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read 
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: eu-west-2 # use your region here.

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color 

    - name: Terraform Apply
      id: Apply
      run: terraform apply -no-color 
    